/* M9 docstrings in the editor: hover and dot-completion, fed by the
 * compiler's own documentation pass.
 *
 * THE ONE RULE: NO SECOND SCANNER.  corpus/Gen.m9 holds 18 string
 * literals containing "(*" or "*)", so any JavaScript regex that
 * walked comments would open a phantom comment at line 1432 and eat
 * 54 lines of declarations -- that experiment is already refuted in
 * the repo's record (docs work, 2026-08-24).  This extension
 * therefore parses NOTHING of M9 itself beyond an identifier under
 * the cursor and the IMPORT lines that name candidate modules; the
 * documentation comes from `m9c --doc`, generated by the real lexer
 * and parser, with the checked-in docs/modules/*.md as the fallback
 * when the compiler is not on hand.
 *
 * Settings (m9.*):
 *   compilerPath   the m9c binary; default resolves
 *                  <workspace>/runtime/test/m9c, then
 *                  <workspace>/out/m9c, then "m9c" on PATH
 *   includePaths   -I directories (a build dir holding Kind.m9 makes
 *                  a port's modules documentable, e.g.
 *                  ~/m9build or /tmp/m9build)
 *   libraryPaths   $M9LIBRARY; default <workspace>/corpus and
 *                  any directory m9.includePaths names
 */
"use strict";
const vscode = require ("vscode");
const cp = require ("child_process");
const fs = require ("fs");
const os = require ("os");
const path = require ("path");

/* ---- the generated-markdown model ---- */

/* Parse one NAME.md as m9c --doc writes it: `# Module`, the module
   comment, then `### <header>` sections.  Headers are one of
   `TYPE Name`, `EXCEPTION Name`, `CONST Name`, `VAR Name`, or a
   procedure `Name (signature...)`. */
function parseDoc (text) {
  const mod = { name: null, doc: "", symbols: new Map () };
  const lines = text.split (/\r?\n/);
  let i = 0;
  while (i < lines.length && !lines[i].startsWith ("# ")) i++;
  if (i < lines.length) { mod.name = lines[i].slice (2).trim (); i++; }
  const chunks = [];
  let cur = null;
  for (; i < lines.length; i++) {
    if (lines[i].startsWith ("### ")) {
      cur = { header: lines[i].slice (4).trim (), body: [] };
      chunks.push (cur);
    } else if (cur) cur.body.push (lines[i]);
    else mod.doc += lines[i] + "\n";
  }
  mod.doc = mod.doc.trim ();
  const order = [];
  for (const c of chunks) {
    let kind = "PROCEDURE", name = c.header, sig = "";
    const m = c.header.match (/^(TYPE|EXCEPTION|CONST|VAR)\s+(\w+)(.*)$/);
    if (m) { kind = m[1]; name = m[2]; sig = m[3].trim (); }
    else {
      const p = c.header.match (/^(\w+)\s*(\(.*)$/s);
      if (p) { name = p[1]; sig = p[2]; }
    }
    const sym = { kind, name, sig, body: c.body.join ("\n").trim () };
    mod.symbols.set (name, sym);
    order.push (sym);
  }
  /* a grouped CONST's placeholder resolves forward to the group's
     shared comment, so hovering any member shows the real text */
  const PLACE = "_(documented with the group below)_";
  for (let k = 0; k < order.length; k++)
    if (order[k].body === PLACE)
      for (let j = k + 1; j < order.length; j++)
        if (order[j].body && order[j].body !== PLACE) {
          order[k].body = order[j].body;
          break;
        }
  return mod;
}

/* ---- configuration and search paths ---- */

function wsRoots () {
  return (vscode.workspace.workspaceFolders || [])
    .map (f => f.uri.fsPath);
}

function config () {
  const c = vscode.workspace.getConfiguration ("m9");
  return {
    compilerPath: c.get ("compilerPath", ""),
    includePaths: c.get ("includePaths", []),
    libraryPaths: c.get ("libraryPaths", []),
  };
}

function firstExisting (cands) {
  for (const p of cands)
    try { if (p && fs.existsSync (p)) return p; } catch (e) {}
  return null;
}

function compilerPath () {
  const c = config ();
  if (c.compilerPath) return c.compilerPath;
  const found = firstExisting (wsRoots ().flatMap (r =>
    [path.join (r, "runtime", "test", "m9c"),
     path.join (r, "out", "m9c")]));
  return found || "m9c";
}

function libraryPaths () {
  const c = config ();
  const dirs = [...c.libraryPaths];
  for (const r of wsRoots ()) {
    dirs.push (path.join (r, "corpus"));
  }
  return dirs.filter (d => { try { return fs.existsSync (d); }
                             catch (e) { return false; } });
}

/* where a module's source lives: the current file's own directory
   first (m9c's own last-resort rule), then -I dirs, then the library
   -- the same order the compiler searches, so the hover documents
   the file the build would use */
function resolveSource (name, hintDir) {
  const cands = [];
  if (hintDir) cands.push (path.join (hintDir, name + ".m9"));
  for (const d of config ().includePaths)
    cands.push (path.join (d, name + ".m9"));
  for (const d of libraryPaths ())
    cands.push (path.join (d, name + ".m9"));
  return firstExisting (cands);
}

/* ---- the doc cache: one m9c --doc run per (source, mtime) ---- */

const cache = new Map ();          /* srcPath -> {mtime, mod} */
let tmpDir = null;

function docFor (name, hintDir) {
  const src = resolveSource (name, hintDir);
  if (src) {
    let mtime = 0;
    try { mtime = fs.statSync (src).mtimeMs; } catch (e) {}
    const hit = cache.get (src);
    if (hit && hit.mtime === mtime) return hit.mod;
    const mod = generate (src, hintDir) || fallback (name);
    if (mod) cache.set (src, { mtime, mod });
    return mod;
  }
  return fallback (name);
}

function generate (src, hintDir) {
  try {
    if (!tmpDir)
      tmpDir = fs.mkdtempSync (path.join (os.tmpdir (), "m9doc-"));
    const args = ["--doc", src];
    for (const d of [hintDir, ...config ().includePaths])
      if (d) args.push ("-I", d);
    const r = cp.spawnSync (compilerPath (), args, {
      cwd: tmpDir,
      env: Object.assign ({}, process.env,
        { M9LIBRARY: libraryPaths ().join (":") }),
      timeout: 15000,
    });
    if (r.status !== 0) return null;
    const md = path.join (tmpDir,
      path.basename (src).replace (/\.m9$/, ".md"));
    return parseDoc (fs.readFileSync (md, "utf8"));
  } catch (e) { return null; }
}

/* the checked-in reference: corpus modules document themselves even
   without a compiler on this machine */
function fallback (name) {
  const p = firstExisting (wsRoots ().map (r =>
    path.join (r, "docs", "modules", name + ".md")));
  if (!p) return null;
  try { return parseDoc (fs.readFileSync (p, "utf8")); }
  catch (e) { return null; }
}

/* ---- what the current file names ---- */

function ownModule (doc) {
  const m = doc.getText ().match (/(?:DEFINITION\s+)?MODULE\s+(\w+)/);
  return m ? m[1] : path.basename (doc.fileName, ".m9");
}

function importedModules (doc) {
  const out = new Set ();
  for (const m of doc.getText ()
       .matchAll (/^\s*(?:IMPORT|FROM)\s+(\w+)/gm))
    out.add (m[1]);
  return out;
}

/* ---- rendering ---- */

function render (modName, sym) {
  const md = new vscode.MarkdownString ();
  const head = sym.kind === "PROCEDURE"
    ? `PROCEDURE ${modName}.${sym.name} ${sym.sig}`
    : `${sym.kind} ${modName}.${sym.name}${sym.sig ? " " + sym.sig : ""}`;
  md.appendCodeblock (head, "m9");
  if (sym.body) md.appendMarkdown ("\n" + sym.body);
  return md;
}

function renderModule (mod) {
  const md = new vscode.MarkdownString ();
  md.appendCodeblock (`MODULE ${mod.name}`, "m9");
  if (mod.doc) md.appendMarkdown ("\n" + mod.doc);
  return md;
}

/* ---- providers ---- */

const hover = {
  provideHover (doc, pos) {
    const range = doc.getWordRangeAtPosition (pos, /[A-Za-z][A-Za-z0-9]*/);
    if (!range) return null;
    const word = doc.getText (range);
    const before = doc.getText (new vscode.Range (
      new vscode.Position (range.start.line, 0), range.start));
    const hintDir = path.dirname (doc.fileName);
    const q = before.match (/([A-Za-z][A-Za-z0-9]*)\.$/);
    if (q) {
      const m = docFor (q[1], hintDir);
      const sym = m && m.symbols.get (word);
      return sym ? new vscode.Hover (render (q[1], sym), range) : null;
    }
    /* a bare module name (hovering an IMPORT, or a qualifier) *
     * shows the module comment                                */
    if (importedModules (doc).has (word)
        || doc.getText (new vscode.Range (range.end,
             new vscode.Position (range.end.line,
                                  range.end.character + 1))) === ".") {
      const m = docFor (word, hintDir);
      if (m) return new vscode.Hover (renderModule (m), range);
    }
    /* otherwise: this module's own exported name */
    const own = ownModule (doc);
    const m = docFor (own, hintDir);
    const sym = m && m.symbols.get (word);
    return sym ? new vscode.Hover (render (own, sym), range) : null;
  },
};

const completion = {
  provideCompletionItems (doc, pos) {
    const before = doc.getText (new vscode.Range (
      new vscode.Position (pos.line, 0), pos));
    const q = before.match (/([A-Za-z][A-Za-z0-9]*)\.$/);
    if (!q) return null;
    if (!importedModules (doc).has (q[1])) return null;
    const m = docFor (q[1], path.dirname (doc.fileName));
    if (!m) return null;
    const kinds = {
      PROCEDURE: vscode.CompletionItemKind.Function,
      TYPE: vscode.CompletionItemKind.Struct,
      CONST: vscode.CompletionItemKind.Constant,
      VAR: vscode.CompletionItemKind.Variable,
      EXCEPTION: vscode.CompletionItemKind.Event,
    };
    const items = [];
    for (const sym of m.symbols.values ()) {
      const it = new vscode.CompletionItem (sym.name,
        kinds[sym.kind] || vscode.CompletionItemKind.Text);
      it.detail = sym.kind === "PROCEDURE" ? sym.sig
                : `${sym.kind}${sym.sig ? " " + sym.sig : ""}`;
      it.documentation = new vscode.MarkdownString (sym.body || "");
      items.push (it);
    }
    return items;
  },
};

function activate (context) {
  context.subscriptions.push (
    vscode.languages.registerHoverProvider ("m9", hover),
    vscode.languages.registerCompletionItemProvider ("m9", completion,
                                                     "."));
}

function deactivate () {}

/* hover/completion exported for the headless test harness
   (tools/vscode-m9/test.js); the extension host uses activate */
module.exports = { activate, deactivate, parseDoc, hover, completion };
