#!/bin/sh
# The generated reference documentation, against what is checked in.
#
# docs/modules/NAME.md is a GOLDEN, exactly as host/fpc/lextest.golden
# and runtime/gen are: it must regenerate byte-identically, so a
# comment edited without regenerating shows up as a diff rather than
# as documentation that quietly stopped matching the code.
#
# THE COVERAGE NUMBER IS PRINTED AND NEVER GATED.  A threshold on how
# much is documented makes `(* obvious *)` a rational move, which is
# the opposite of the point.  What IS gated is drift -- a `name --`
# line naming something that is not a parameter of that procedure --
# because that is the documentation and the signature disagreeing,
# not a gap.  Same asymmetry mandiff enforces between --help and the
# manual page, applied in the one direction that is safe.
#
# It builds its own m9c rather than accepting one it finds.  mandiff
# takes $M9C, then ./m9c, then ../../out/m9c, and any of those can be
# left over from an earlier run; the project's "THE GATES WERE TESTING
# STALE CODE" is the reason not to repeat that here.
set -e
cd "$(dirname "$0")"
. ./gen.sh          # runtime/gen is BUILT here, not found

gcc -std=c11 -Wall -Wextra -Werror -Wno-unused-label \
    -Wno-unused-parameter -Wno-unused-function \
    -iquote .. -iquote ../gen ../m9rt.c ../gen/DynStr.c ../gen/Io.c \
    ../gen/Lex.c ../gen/Ast.c ../gen/Parse.c ../gen/Print.c ../gen/Text.c \
    ../gen/Fmt.c ../gen/Sem.c ../gen/Gen.c ../gen/Doc.c ../gen/M9c.c -o m9c

M9C=$(pwd)/m9c
SRC=$(cd ../../corpus && pwd)
GOLD=$(cd ../.. && pwd)/docs/modules
OUT=/tmp/m9c-doc
rm -rf "$OUT"; mkdir -p "$OUT"
export M9RUNTIME=$(cd .. && pwd)
export M9LIBRARY=$SRC

# HttpServer names Http explicitly: it says FROM csock IMPORT, csock is
# declared in Http.m9, and `FROM u IMPORT` is deliberately not resolved
# through the search path -- u is a C-backed unit and looking for a
# u.m9 would invent one.  gendiff names it for the same reason.
deps_of () {
  case $1 in
    HttpServer) echo Http DynStr ;;
    *)          echo ;;
  esac
}

n=0; np=0; npd=0; no=0; nod=0; npl=0; drift=0
for m in $(sed -n '/^LIBRARY=/,/Plot ZarrStore"/p' ../../build.sh |
           sed 's/LIBRARY="//; s/"$//; s/\\$//' | tr -s ' \n' ' '); do
  d=""
  for x in $(deps_of "$m"); do d="$d $SRC/$x.m9"; done
  # shellcheck disable=SC2086
  ( cd "$OUT" && "$M9C" -v --doc "$SRC/$m.m9" $d ) 2> "$OUT/$m.stats"
  [ -f "$OUT/$m.md" ] || { echo "docdiff: $m produced no document"; exit 1; }
  if [ -f "$GOLD/$m.md" ]; then
    cmp "$OUT/$m.md" "$GOLD/$m.md" || { echo "DIVERGES: $m.md"; exit 1; }
  else
    echo "docdiff: no golden for $m -- run runtime/test/docgen.sh"; exit 1
  fi
  set -- $(sed -n "s|^doc $m procs \([0-9]*\)/\([0-9]*\) others \([0-9]*\)/\([0-9]*\) paramlines \([0-9]*\) drift \([0-9]*\)$|\1 \2 \3 \4 \5 \6|p" "$OUT/$m.stats")
  npd=$((npd + ${1:-0})); np=$((np + ${2:-0}))
  nod=$((nod + ${3:-0})); no=$((no + ${4:-0}))
  npl=$((npl + ${5:-0})); drift=$((drift + ${6:-0}))
  n=$((n + 1))
done

echo "docdiff: $n modules regenerated byte-identically"
echo "docdiff: procedures $npd/$np documented, other declarations $nod/$no,"
echo "         $npl parameter lines, $drift naming no parameter"
[ "$drift" -eq 0 ] || { echo "docdiff: documented parameters that do not exist"; exit 1; }
